//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientAgence.ServiceHotel {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceHotel.ServiceHotelSoap")]
    public interface ServiceHotelSoap {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément idAgence de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsulterDisponibilité", ReplyAction="*")]
        ClientAgence.ServiceHotel.ConsulterDisponibilitéResponse ConsulterDisponibilité(ClientAgence.ServiceHotel.ConsulterDisponibilitéRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsulterDisponibilité", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientAgence.ServiceHotel.ConsulterDisponibilitéResponse> ConsulterDisponibilitéAsync(ClientAgence.ServiceHotel.ConsulterDisponibilitéRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément idAgence de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Reserver", ReplyAction="*")]
        ClientAgence.ServiceHotel.ReserverResponse Reserver(ClientAgence.ServiceHotel.ReserverRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Reserver", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientAgence.ServiceHotel.ReserverResponse> ReserverAsync(ClientAgence.ServiceHotel.ReserverRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément SendImageResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendImage", ReplyAction="*")]
        ClientAgence.ServiceHotel.SendImageResponse SendImage(ClientAgence.ServiceHotel.SendImageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendImage", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientAgence.ServiceHotel.SendImageResponse> SendImageAsync(ClientAgence.ServiceHotel.SendImageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsulterDisponibilitéRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsulterDisponibilité", Namespace="http://tempuri.org/", Order=0)]
        public ClientAgence.ServiceHotel.ConsulterDisponibilitéRequestBody Body;
        
        public ConsulterDisponibilitéRequest() {
        }
        
        public ConsulterDisponibilitéRequest(ClientAgence.ServiceHotel.ConsulterDisponibilitéRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsulterDisponibilitéRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idAgence;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mdpAgence;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int nbPers;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime dA;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime dD;
        
        public ConsulterDisponibilitéRequestBody() {
        }
        
        public ConsulterDisponibilitéRequestBody(string idAgence, string mdpAgence, int nbPers, System.DateTime dA, System.DateTime dD) {
            this.idAgence = idAgence;
            this.mdpAgence = mdpAgence;
            this.nbPers = nbPers;
            this.dA = dA;
            this.dD = dD;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsulterDisponibilitéResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsulterDisponibilitéResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientAgence.ServiceHotel.ConsulterDisponibilitéResponseBody Body;
        
        public ConsulterDisponibilitéResponse() {
        }
        
        public ConsulterDisponibilitéResponse(ClientAgence.ServiceHotel.ConsulterDisponibilitéResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsulterDisponibilitéResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientAgence.ServiceHotel.ArrayOfString ConsulterDisponibilitéResult;
        
        public ConsulterDisponibilitéResponseBody() {
        }
        
        public ConsulterDisponibilitéResponseBody(ClientAgence.ServiceHotel.ArrayOfString ConsulterDisponibilitéResult) {
            this.ConsulterDisponibilitéResult = ConsulterDisponibilitéResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReserverRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Reserver", Namespace="http://tempuri.org/", Order=0)]
        public ClientAgence.ServiceHotel.ReserverRequestBody Body;
        
        public ReserverRequest() {
        }
        
        public ReserverRequest(ClientAgence.ServiceHotel.ReserverRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReserverRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idAgence;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mdpAgence;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int numOffre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string nom;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime dA;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.DateTime dD;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int nbPers;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string prenom;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string numCarte;
        
        public ReserverRequestBody() {
        }
        
        public ReserverRequestBody(string idAgence, string mdpAgence, int numOffre, string nom, System.DateTime dA, System.DateTime dD, int nbPers, string prenom, string numCarte) {
            this.idAgence = idAgence;
            this.mdpAgence = mdpAgence;
            this.numOffre = numOffre;
            this.nom = nom;
            this.dA = dA;
            this.dD = dD;
            this.nbPers = nbPers;
            this.prenom = prenom;
            this.numCarte = numCarte;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReserverResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReserverResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientAgence.ServiceHotel.ReserverResponseBody Body;
        
        public ReserverResponse() {
        }
        
        public ReserverResponse(ClientAgence.ServiceHotel.ReserverResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReserverResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ReserverResult;
        
        public ReserverResponseBody() {
        }
        
        public ReserverResponseBody(string ReserverResult) {
            this.ReserverResult = ReserverResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendImageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendImage", Namespace="http://tempuri.org/", Order=0)]
        public ClientAgence.ServiceHotel.SendImageRequestBody Body;
        
        public SendImageRequest() {
        }
        
        public SendImageRequest(ClientAgence.ServiceHotel.SendImageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SendImageRequestBody {
        
        public SendImageRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendImageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendImageResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientAgence.ServiceHotel.SendImageResponseBody Body;
        
        public SendImageResponse() {
        }
        
        public SendImageResponse(ClientAgence.ServiceHotel.SendImageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendImageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendImageResult;
        
        public SendImageResponseBody() {
        }
        
        public SendImageResponseBody(string SendImageResult) {
            this.SendImageResult = SendImageResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceHotelSoapChannel : ClientAgence.ServiceHotel.ServiceHotelSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceHotelSoapClient : System.ServiceModel.ClientBase<ClientAgence.ServiceHotel.ServiceHotelSoap>, ClientAgence.ServiceHotel.ServiceHotelSoap {
        
        public ServiceHotelSoapClient() {
        }
        
        public ServiceHotelSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceHotelSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceHotelSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceHotelSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientAgence.ServiceHotel.ConsulterDisponibilitéResponse ClientAgence.ServiceHotel.ServiceHotelSoap.ConsulterDisponibilité(ClientAgence.ServiceHotel.ConsulterDisponibilitéRequest request) {
            return base.Channel.ConsulterDisponibilité(request);
        }
        
        public ClientAgence.ServiceHotel.ArrayOfString ConsulterDisponibilité(string idAgence, string mdpAgence, int nbPers, System.DateTime dA, System.DateTime dD) {
            ClientAgence.ServiceHotel.ConsulterDisponibilitéRequest inValue = new ClientAgence.ServiceHotel.ConsulterDisponibilitéRequest();
            inValue.Body = new ClientAgence.ServiceHotel.ConsulterDisponibilitéRequestBody();
            inValue.Body.idAgence = idAgence;
            inValue.Body.mdpAgence = mdpAgence;
            inValue.Body.nbPers = nbPers;
            inValue.Body.dA = dA;
            inValue.Body.dD = dD;
            ClientAgence.ServiceHotel.ConsulterDisponibilitéResponse retVal = ((ClientAgence.ServiceHotel.ServiceHotelSoap)(this)).ConsulterDisponibilité(inValue);
            return retVal.Body.ConsulterDisponibilitéResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientAgence.ServiceHotel.ConsulterDisponibilitéResponse> ClientAgence.ServiceHotel.ServiceHotelSoap.ConsulterDisponibilitéAsync(ClientAgence.ServiceHotel.ConsulterDisponibilitéRequest request) {
            return base.Channel.ConsulterDisponibilitéAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientAgence.ServiceHotel.ConsulterDisponibilitéResponse> ConsulterDisponibilitéAsync(string idAgence, string mdpAgence, int nbPers, System.DateTime dA, System.DateTime dD) {
            ClientAgence.ServiceHotel.ConsulterDisponibilitéRequest inValue = new ClientAgence.ServiceHotel.ConsulterDisponibilitéRequest();
            inValue.Body = new ClientAgence.ServiceHotel.ConsulterDisponibilitéRequestBody();
            inValue.Body.idAgence = idAgence;
            inValue.Body.mdpAgence = mdpAgence;
            inValue.Body.nbPers = nbPers;
            inValue.Body.dA = dA;
            inValue.Body.dD = dD;
            return ((ClientAgence.ServiceHotel.ServiceHotelSoap)(this)).ConsulterDisponibilitéAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientAgence.ServiceHotel.ReserverResponse ClientAgence.ServiceHotel.ServiceHotelSoap.Reserver(ClientAgence.ServiceHotel.ReserverRequest request) {
            return base.Channel.Reserver(request);
        }
        
        public string Reserver(string idAgence, string mdpAgence, int numOffre, string nom, System.DateTime dA, System.DateTime dD, int nbPers, string prenom, string numCarte) {
            ClientAgence.ServiceHotel.ReserverRequest inValue = new ClientAgence.ServiceHotel.ReserverRequest();
            inValue.Body = new ClientAgence.ServiceHotel.ReserverRequestBody();
            inValue.Body.idAgence = idAgence;
            inValue.Body.mdpAgence = mdpAgence;
            inValue.Body.numOffre = numOffre;
            inValue.Body.nom = nom;
            inValue.Body.dA = dA;
            inValue.Body.dD = dD;
            inValue.Body.nbPers = nbPers;
            inValue.Body.prenom = prenom;
            inValue.Body.numCarte = numCarte;
            ClientAgence.ServiceHotel.ReserverResponse retVal = ((ClientAgence.ServiceHotel.ServiceHotelSoap)(this)).Reserver(inValue);
            return retVal.Body.ReserverResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientAgence.ServiceHotel.ReserverResponse> ClientAgence.ServiceHotel.ServiceHotelSoap.ReserverAsync(ClientAgence.ServiceHotel.ReserverRequest request) {
            return base.Channel.ReserverAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientAgence.ServiceHotel.ReserverResponse> ReserverAsync(string idAgence, string mdpAgence, int numOffre, string nom, System.DateTime dA, System.DateTime dD, int nbPers, string prenom, string numCarte) {
            ClientAgence.ServiceHotel.ReserverRequest inValue = new ClientAgence.ServiceHotel.ReserverRequest();
            inValue.Body = new ClientAgence.ServiceHotel.ReserverRequestBody();
            inValue.Body.idAgence = idAgence;
            inValue.Body.mdpAgence = mdpAgence;
            inValue.Body.numOffre = numOffre;
            inValue.Body.nom = nom;
            inValue.Body.dA = dA;
            inValue.Body.dD = dD;
            inValue.Body.nbPers = nbPers;
            inValue.Body.prenom = prenom;
            inValue.Body.numCarte = numCarte;
            return ((ClientAgence.ServiceHotel.ServiceHotelSoap)(this)).ReserverAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientAgence.ServiceHotel.SendImageResponse ClientAgence.ServiceHotel.ServiceHotelSoap.SendImage(ClientAgence.ServiceHotel.SendImageRequest request) {
            return base.Channel.SendImage(request);
        }
        
        public string SendImage() {
            ClientAgence.ServiceHotel.SendImageRequest inValue = new ClientAgence.ServiceHotel.SendImageRequest();
            inValue.Body = new ClientAgence.ServiceHotel.SendImageRequestBody();
            ClientAgence.ServiceHotel.SendImageResponse retVal = ((ClientAgence.ServiceHotel.ServiceHotelSoap)(this)).SendImage(inValue);
            return retVal.Body.SendImageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientAgence.ServiceHotel.SendImageResponse> ClientAgence.ServiceHotel.ServiceHotelSoap.SendImageAsync(ClientAgence.ServiceHotel.SendImageRequest request) {
            return base.Channel.SendImageAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientAgence.ServiceHotel.SendImageResponse> SendImageAsync() {
            ClientAgence.ServiceHotel.SendImageRequest inValue = new ClientAgence.ServiceHotel.SendImageRequest();
            inValue.Body = new ClientAgence.ServiceHotel.SendImageRequestBody();
            return ((ClientAgence.ServiceHotel.ServiceHotelSoap)(this)).SendImageAsync(inValue);
        }
    }
}
